project_id = "femtmeufuuwrwachkjux"

[functions.sync-eregnskab]
verify_jwt = false

[functions.fetch-appointments]
verify_jwt = false

[functions.fetch-categories]
verify_jwt = false

[functions.fetch-hourly-employees]
verify_jwt = false

[functions.fetch-user-by-id]
verify_jwt = false

[functions.check-today]
verify_jwt = false

[functions.remind-yesterday]
verify_jwt = false

[functions.friday-summary]
verify_jwt = false

[functions.sync-registrations]
verify_jwt = false

[functions.sync-reference-data]
verify_jwt = false

[functions.cleanup-stale-cases]
verify_jwt = false
