// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://femtmeufuuwrwachkjux.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZlbXRtZXVmdXV3cndhY2hranV4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzM5MTIxOTYsImV4cCI6MjA4OTQ4ODE5Nn0.HwvWpC_Pp4zgVByTeEKmXHU3bsgw-tEGbNUo4Ouvc_U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});