// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xwxpbowfodnjienzrigj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh3eHBib3dmb2RuamllbnpyaWdqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQxNzg3MDUsImV4cCI6MjA1OTc1NDcwNX0.NHC7608u4HEo7WKFTjVFfxGjgslqKpOAW0658IAimq4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);